Resources:
    MySecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: My Newly created security group
            GroupName: Mr bma secured group access
            SecurityGroupEgress: 
              - IpProtocol: '-1'
                CidrIp: 0.0.0.0/0                                     
            SecurityGroupIngress: 
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 0.0.0.0/0
            VpcId: vpc-0976a15a205c02dce















































